### ISSUE TITLE
Test suite logs MaxListenersExceededWarning

### ISSUE THREAD

**Issue by djones** [percy/percy-agent#187]
```bash
(node:29441) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at WriteStream.addListener (events.js:297:10)
    at WriteStream.Readable.on (_stream_readable.js:772:35)
    at Snapshot._swallowEPIPE (/Users/djones/Code/percy-agent/node_modules/@oclif/command/lib/command.js:133:24)
    at Snapshot.init (/Users/djones/Code/percy-agent/node_modules/@oclif/command/lib/command.js:67:14)
    at Snapshot._run (/Users/djones/Code/percy-agent/node_modules/@oclif/command/lib/command.js:33:24)
    at Function.Command.run (/Users/djones/Code/percy-agent/node_modules/@oclif/command/lib/command.js:155:16)
    at <anonymous>
```

This issue looks pretty related https://github.com/forcedotcom/cli/issues/30

And the Heroku CLI test runs have this same warning https://ci.appveyor.com/project/heroku/heroku-cli-command/branch/master#L174

Both Force.com and Heroku CLIs are using Oclif.

**Comment by djones** [comment]
I believe this issue may have been introduced with https://github.com/oclif/command/pull/54

**Comment by djones** [comment]
Filed an issue for this https://github.com/oclif/command/issues/63
