### ISSUE TITLE
UnhandledPromiseRejectionWarning running `percy snapshot` since 0.26.3

### ISSUE THREAD

**Issue by orangejulius** [percy/percy-agent#509]
Hi folks :wave:,

We've been happily using percy-agent to snapshot our Jekyll static site until yesterday when version [0.26.3](https://github.com/percy/percy-agent/releases/tag/v0.26.3) was published. Since then we've been getting the following error:

```
$ npx percy snapshot _site/
(node:17931) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/travis/.npm/_npx/17899/lib/node_modules/percy/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/.npm/_npx/17899/lib/node_modules/percy/node_modules/puppeteer/lib/BrowserFetcher.js:25:20)
(node:17931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.<anonymous> (~/.npm/_npx/17899/lib/node_modules/percy/node_modules/extract-zip/index.js:11:18)
    at Object.<anonymous> (~/.npm/_npx/17899/lib/node_modules/percy/node_modules/puppeteer/lib/BrowserFetcher.js:25:20)
The command "npx percy snapshot _site/" exited with 1.
```

Downgrading to 0.26.2 fixed the issue, so we're all good for now. 0.26.4 looks like it fixed a similar issue, but didn't resolve this error for us.

Let us know if we can help you track anything down or if it's something with how we're using the percy-agent. Maybe we shouldn't run it directly via `npx`?

**Comment by orangejulius** [comment]
Hi again!

Turns out the TravisCI environment we were running these builds on was defaulting to Node.js 8, which is EOL and your engines specification shows you [don't support](https://github.com/percy/percy-agent/blob/06dc067e7ac87b04ae6b9350d5f547ba943cc81c/package.json#L116).

Upgrading to Node.js 12 fixed things. So feel free to close this if Node.js 8 isn't something you want to support.

**Comment by Robdel12** [comment]
Hey @orangejulius! I was meaning to comment and mention this sounds like a node version issue. Happy it was worked out before that! 😃 

We don't support Node 8 since it was EOL'd on January 1st, 2020 (we don't want to support anything that doesn't get security patches/support). In _theory_ things should work if the engine is ignored (we're not using any special APIs).
