### ISSUE TITLE
Unable to install do to puppeteer errors

### ISSUE THREAD

**Issue by alphex** [percy/percy-agent#514]
On OSX 10.15.4

```
sudo npm install -g @percy/agent
```

results in

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/percy -> /usr/local/lib/node_modules/@percy/agent/bin/run

> puppeteer@3.1.0 install /usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/lib/helper.js:94:19)
    at fetchBinary (/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/install.js:148:8)
    at download (/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/install.js:54:9)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/@percy/agent/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/duran/.npm/_logs/2020-05-28T02_55_52_122Z-debug.log
```

I track down this command

```
sudo npm install -g puppeteer --unsafe-perm=true
```

This runs with no errors.
Then I try to run `sudo npm install -g @percy/agent` again, same error.

I try to run `sudo npm install -g @percy/agent --PUPPETEER_SKIP_DOWNLOAD=1` as a shot in the dark, same error.

How can I get this installed?
Thank you.

**Comment by wwilsman** [comment]
Hi @alphex!

The `--unsafe-perm` flag is an [npm configuration option](https://docs.npmjs.com/misc/config#unsafe-perm) that suppresses user/group switching when running package scripts. When npm is invoked with root privileges, it will change the user to the user account or uid specified by the user config, which defaults to nobody. The `--unsafe-perm` flag allows scripts like puppeteer's install script to run with root privileges.

Since it's an npm flag, try it when installing `@percy/agent`:

```sh-session
$ sudo npm install -g @percy/agent --unsafe-perm=true
```

**Comment by alphex** [comment]
@wwilsman  that solved the problem, thank you.
